// Mock template content generator
export const getTemplateContent = (templateName: string, domainId: string, type: string = 'domain'): string => {
  const baseContent = `# ${templateName}

## Overview
This template provides comprehensive guidance for implementing ${domainId} domain requirements in accordance with CMMC 2.0 Level 2 standards.

## Purpose
The purpose of this document is to establish clear procedures and guidelines for ${domainId} implementation within our organization.

## Scope
This document applies to all systems, personnel, and processes that handle Controlled Unclassified Information (CUI) within the ${domainId} domain.

## Responsibilities
- **System Owner**: Responsible for overall implementation
- **Security Team**: Responsible for technical implementation
- **Compliance Officer**: Responsible for oversight and monitoring

## Implementation Requirements

### Control Requirements
- Implement appropriate ${domainId} controls
- Establish monitoring and logging
- Regular review and updates
- Documentation and evidence collection

### Procedures
1. **Initial Setup**
   - Assess current state
   - Identify gaps
   - Develop implementation plan

2. **Implementation**
   - Deploy controls
   - Configure monitoring
   - Train personnel

3. **Monitoring**
   - Regular reviews
   - Performance metrics
   - Continuous improvement

## Evidence Collection
The following evidence should be collected to demonstrate compliance:
- Policy documents
- Configuration screenshots
- Training records
- Audit logs
- Test results

## Review and Updates
This document should be reviewed annually or when significant changes occur.

## Approval
- **Prepared by**: [Name]
- **Reviewed by**: [Name]
- **Approved by**: [Name]
- **Date**: ${new Date().toLocaleDateString()}

---

*This document is part of the CyberCertitude™ CMMC 2.0 Compliance Toolkit by ERMITS.*`;

  if (type === 'scenario') {
    return `# ${templateName}

## Executive Summary
${templateName} is a comprehensive enterprise document designed to provide detailed guidance for implementing robust security controls and procedures.

## Table of Contents
1. Introduction
2. Scope and Objectives
3. Implementation Guidelines
4. Procedures and Workflows
5. Evidence Collection
6. Monitoring and Review
7. Appendices

## Introduction
This document provides detailed implementation guidance for ${templateName}. It includes step-by-step procedures, forms, checklists, and examples to ensure successful implementation.

## Implementation Guidelines
- Follow all procedures exactly as documented
- Collect evidence at each step
- Document all decisions and rationale
- Maintain version control

## Procedures
[Detailed procedures would be included here]

## Evidence Collection
- Policy documents
- Implementation screenshots
- Training materials
- Audit logs
- Test results
- Approval signatures

## Monitoring and Review
Regular monitoring and review processes are essential for maintaining compliance.

---

*Generated by CyberCertitude™ CMMC 2.0 Compliance Toolkit by ERMITS*`;
  }

  return baseContent;
};
